name: 'mGBA ROM Test'
description: 'Unit testing for Game Boy Advance ROMs'
inputs:
  swi-call:
    description: 'Software Interrupt that ends the test'
    required: true
    default: 3
  read-register:
    description: 'General purpose register to return as exit code'
    required: true
    default: 'r0'
  rom-path:
    description: 'Game Boy Advance ROM path'
    required: true
  success-code:
    description: 'Expected value in read-register'
    required: false
    default: 0
outputs:
  exitcode:
    description: 'Test exit code'
    value: ${{ steps.mgba-rom-test.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - id: download
      shell: bash
      run: |
        mkdir tmp-download
        curl -LsSf https://s3.amazonaws.com/mgba/mGBA-build-latest-ubuntu64-noble.tar.xz | tar -Jxf - -C tmp-download
    - id: extract
      shell: bash
      run: |
        mkdir mgba
        find tmp-download/ -type f -exec mv -i {} mgba/. \;
    - id: install
      shell: bash
      run: |
        set +e
        sudo dpkg -i mgba/libmgba.deb
        sudo dpkg -i mgba/mgba-headless.deb
        set -e
        sudo apt-get update && sudo apt-get install -f
    - id: mgba-headless
      shell: bash
      run: |
        set +e
        mgba-headless -S ${{ inputs.swi-call }} -R ${{ inputs.read-register }} ${{ inputs.rom-path }}
        rom_test_exitcode=$?
        set -e
        echo "name=exitcode::$rom_test_exitcode" >> $GITHUB_OUTPUT
        if [[ $rom_test_exitcode == ${{ inputs.success-code }} ]]; then exit 0; else exit 1; fi
